**** JK 03-10-11 11:11:04 

/*  Program ......:                  _APPX.CH

    Authors.......: Thomas Leylan, C Parry, John Kirby
    Date..........: 25/12/1994
*/

/*define box structure */

#define BX_TOP    1
#define BX_LEFT   2
#define BX_HEIGHT 3
#define BX_WIDTH  4
#define BX_FRAME  5
#define BX_COLOR  6
#define BX_TITLE  7
#define BX_SHADOW 8
#define BX_IMAGE  9

*******--------------------  END OF FILE APPX.CH